'use client';
import { useEffect, useRef, useState } from 'react';
import { X, ArrowUpRight, Check, ChevronLeft, Music2, Link2, Bookmark, History } from 'lucide-react';
import { musicProviders, type ProviderId, type ProviderPlaylist, type ProviderProfile } from '@/services/musicProviders';
import { useExploration } from '@/store/exploration';
import { activePath } from '@/graph/session';
import { tracks } from '@/mocks/tracks';
import { Artwork } from './Artwork';
export type Panel = 'services' | 'playlists' | 'history' | null;
export function LibraryPanel({ panel, onClose }: { panel: Panel; onClose(): void }) {
  const dialog = useRef<HTMLDialogElement>(null); const [profiles,setProfiles] = useState<Partial<Record<ProviderId,ProviderProfile | null>>>({}); const [provider,setProvider] = useState<ProviderId>('spotify'); const [playlists,setPlaylists] = useState<ProviderPlaylist[]>([]); const [playlist,setPlaylist] = useState<ProviderPlaylist | null>(null); const [busy,setBusy] = useState(false); const [error,setError] = useState('');
  const session = useExploration(s => s.session); const saved = useExploration(s => s.saved);
  useEffect(() => { if (panel) { dialog.current?.showModal(); setPlaylist(null); setError(''); void Promise.all(Object.values(musicProviders).map(async p => [p.id, await p.getUserProfile()])).then(entries => setProfiles(Object.fromEntries(entries))).catch(() => setError('Connections are unavailable in this browser.')); } else dialog.current?.close(); }, [panel]);
  useEffect(() => { let live = true; setPlaylists([]); if (panel === 'playlists') void musicProviders[provider].getPlaylists().then(p => { if (live) setPlaylists(p); }).catch(() => { if (live) setError('Your library could not load. Please try again.'); }); return () => { live = false; }; }, [panel,provider,profiles]);
  async function connect(id: ProviderId) { setBusy(true); setError(''); try { const p = musicProviders[id]; if (profiles[id]) await p.disconnect(); else await p.connect(); setProfiles(prev => ({ ...prev,[id]:null })); const profile = await p.getUserProfile(); setProfiles(prev => ({ ...prev,[id]:profile })); } catch { setError('The demo connection could not be saved. Check browser storage access.'); } finally { setBusy(false); } }
  return <dialog aria-labelledby="library-heading" ref={dialog} className="library-dialog" onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) { const r = e.currentTarget.getBoundingClientRect(); if (e.clientX < r.left || e.clientX > r.right || e.clientY < r.top || e.clientY > r.bottom) onClose(); } }}><div className="dialog-top"><div className="eyebrow">YOUR SPACE</div><button aria-label="Close panel" onClick={onClose}><X size={18}/></button></div><h2 id="library-heading">{panel === 'services' ? 'Bring your world along.' : panel === 'history' ? 'The places you’ve been.' : playlist ? playlist.name : 'Start with a familiar feeling.'}</h2><p className="dialog-description">{panel === 'services' ? 'Connect a music service to explore from your library.' : panel === 'history' ? 'Every turn is part of your story. Return to any song.' : 'Your playlists are a door to somewhere new.'}</p>
  {error && <p role="alert" className="error-text">{error}</p>}
  {panel === 'services' && <><div className="service-list">{(['spotify','appleMusic'] as const).map(id => <div className="service-row" key={id}><span className={`service-icon ${id}`}><Music2 size={21}/></span><span><strong>{id === 'spotify' ? 'Spotify' : 'Apple Music'}</strong><small>{profiles[id] ? 'Demo connected' : 'Not connected'}</small></span><button className={profiles[id] ? 'subtle-button' : 'primary-button'} disabled={busy} onClick={() => void connect(id)}>{profiles[id] ? <Check size={13}/> : <Link2 size={13}/>} {profiles[id] ? 'Disconnect' : `Connect ${id === 'spotify' ? 'Spotify' : 'Apple Music'}`}</button></div>)}</div><p className="demo-explanation">You’re in the demo. Connecting opens a sample library and does not sign in to your real music account.</p></>}
  {panel === 'playlists' && <><div className="provider-tabs">{(['spotify','appleMusic'] as const).map(id => <button key={id} className={provider === id ? 'selected' : ''} onClick={() => { setProvider(id); setPlaylist(null); }}>{id === 'spotify' ? 'Spotify' : 'Apple Music'} {profiles[id] && <span className="live-dot"/>}</button>)}</div>{!profiles[provider] ? <div className="panel-empty"><Music2 size={30}/><h3>Your library, a new perspective.</h3><p>Connect the demo library to choose an exploration seed.</p><button className="primary-button" disabled={busy} onClick={() => void connect(provider)}>Connect {provider === 'spotify' ? 'Spotify' : 'Apple Music'}</button><small>No account required · sample playlists only</small></div> : playlist ? <><button className="back-button" onClick={() => setPlaylist(null)}><ChevronLeft size={14}/>All playlists</button><div className="track-list">{playlist.tracks.map(track => <button key={track.id} onClick={() => { void useExploration.getState().start(track,{ providerId:provider,playlistId:playlist.id }); onClose(); }}><Artwork track={track}/><span><strong>{track.title}</strong><small>{track.artists[0].name}</small></span><ArrowUpRight size={15}/></button>)}</div></> : <div className="playlist-list">{playlists.map(p => <button key={p.id} onClick={() => setPlaylist(p)}><Artwork track={p.tracks[0]}/><span><strong>{p.name}</strong><small>{p.description}</small><small>{p.tracks.length} songs · demo playlist</small></span><ArrowUpRight size={16}/></button>)}</div>}</>}
  {panel === 'history' && <><div className="section-label"><History size={13}/>CURRENT EXPLORATION<span>{session ? session.nodes.filter(n => n.expanded).length : 0} explored</span></div>{session ? <><div className="history-path">{activePath(session).map(n => n.track.title).join(' → ')}</div><div className="track-list">{session.nodes.filter(n => n.expanded || n.nodeId === session.activeNodeId).map(n => <button key={n.nodeId} onClick={() => { void useExploration.getState().expand(n.nodeId); onClose(); }}><Artwork track={n.track}/><span><strong>{n.track.title}</strong><small>{n.track.artists[0].name} · {n.depth === 0 ? 'Starting point' : `Step ${n.depth + 1}`}</small></span>{n.nodeId === session.activeNodeId ? <span className="live-dot"/> : <ArrowUpRight size={15}/>}</button>)}</div></> : <p className="empty-copy">Your first discovery is waiting. Search for a song to begin.</p>}<div className="section-label"><Bookmark size={13}/>SAVED SONGS<span>{saved.length}</span></div><div className="track-list">{saved.map(id => session?.nodes.find(n => n.track.id === id)?.track || tracks.find(t => t.id === id)).filter(t => !!t).map(track => <button key={track.id} onClick={() => { const n = session?.nodes.find(n => n.track.id === track.id); if (n) void useExploration.getState().expand(n.nodeId); else void useExploration.getState().start(track); onClose(); }}><Artwork track={track}/><span><strong>{track.title}</strong><small>{track.artists[0].name}</small></span><ArrowUpRight size={15}/></button>)}</div>{!saved.length && <p className="empty-copy">Save a song with + to keep it here, across explorations.</p>}<p className="demo-explanation">Your current map and saved songs stay in this browser. A new exploration replaces the current map.</p></>}
  </dialog>;
}
