import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { canonicalJson, canonicalSha256 } from '../src/research-export/canonical';
import { SOURCE_FILES_V2 } from '../src/research-export/schemaV2';
import { fmaCatalog } from '../src/catalog/fma40';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

function fileSha(rel: string): string {
  return createHash('sha256').update(readFileSync(join(repoRoot, rel))).digest('hex');
}

function gitState(): { commit: string | null; dirty: boolean | null } {
  try {
    const commit = execFileSync('git', ['rev-parse', 'HEAD'], {
      cwd: repoRoot, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    if (!/^[0-9a-f]{40}$/.test(commit)) return { commit: null, dirty: null };
    const status = execFileSync('git', ['status', '--porcelain'], {
      cwd: repoRoot, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
    });
    return { commit, dirty: status.length > 0 };
  } catch {
    return { commit: null, dirty: null };
  }
}

async function main(): Promise<void> {
  const git = gitState();
  const source_files: Record<string, string> = {};
  for (const rel of SOURCE_FILES_V2) source_files[rel] = fileSha(rel);
  const catalog = fmaCatalog.map(item => ({
    id: item.id, title: item.title, artists: item.artists, genre_ids: item.genre_ids, genre_names: item.genre_names,
    source_url: item.source_url, license_url: item.license_url, audio_sha256: item.audio_sha256, preview_duration_ms: item.preview_duration_ms,
  }));
  const catalog_sha256 = await canonicalSha256(catalog);
  const body = `/* Generated by scripts/write-provenance.ts. Do not edit. Excluded from source_files. */\nexport const PROVENANCE = ${canonicalJson({
    commit: git.commit, dirty: git.dirty, source_files, catalog_sha256,
  })} as const;\n`;
  writeFileSync(join(repoRoot, 'src/research-export/provenance.generated.ts'), body);
  console.log(`wrote provenance catalog=${catalog_sha256.slice(0, 12)} commit=${git.commit ?? 'null'}`);
}

void main();
